NeedDataCommunityWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.blogs.urls')),
    path('^tinymce/', include('tinymce.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blogs/urls.py
from django.urls import path
from apps.blogs.views import IndexView, BlogPostListView, BlogPostDetailView, CourseListView, CourseDetailView, WorkshopListView, WorkshopDetailView, contact_us


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('blogs', BlogPostListView.as_view(), name='blogpost-list'),
    path('blogs/<int:pk>', BlogPostDetailView.as_view(), name='blogpost-detail'),
    path('courses', CourseListView.as_view(), name='course-list'),
    path('courses/<int:pk>', CourseDetailView.as_view(), name='course-detail'),
    path('workshops', WorkshopListView.as_view(), name='workshop-list'),
    path('workshops/<int:pk>', WorkshopDetailView.as_view(), name='workshop-detail'),
    path('contact-us', contact_us, name='contact-us'),
]

apps/accounts/models.py
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    profile = models.ImageField(upload_to='teams')

    def __str__(self):
        return self.name

apps/blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from enum import Enum
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField

    
class BlogPost(models.Model):
    class Tags(models.TextChoices):
        DATA_SCIENCE = 'DATA_SCIENCE', _('Data Science')
        DATA_ANALYSIS = 'DATA_ANALYSIS', _('Data Analysis')
        DATA_VISUALIZATION = 'DATA_VISUALIZATION', _('Data Visualization')
        MACHINE_LEARNING = 'MACHINE_LEARNING', _('Machine Learning')
        DEEP_LEARNING = 'DEEP_LEARNING', _('Deep Learning')
        ARTIFICIAL_INTELLIGENCE = 'ARTIFICIAL_INTELLIGENCE', _('Artificial Intelligence')
        NEURAL_NETWORKS = 'NEURAL_NETWORKS', _('Neural Networks')
        NATURAL_LANGUAGE_PROCESSING = 'NATURAL_LANGUAGE_PROCESSING', _('Natural Language Processing')
        COMPUTER_VISION = 'COMPUTER_VISION', _('Computer Vision')
        REINFORCEMENT_LEARNING = 'REINFORCEMENT_LEARNING', _('Reinforcement Learning')
        BIG_DATA = 'BIG_DATA', _('Big Data')
        CLOUD_COMPUTING = 'CLOUD_COMPUTING', _('Cloud Computing')
        INTERNET_OF_THINGS = 'INTERNET_OF_THINGS', _('Internet of Things')
        BLOCKCHAIN = 'BLOCKCHAIN', _('Blockchain')
        CYBER_SECURITY = 'CYBER_SECURITY', _('Cyber Security')
        WEB_DEVELOPMENT = 'WEB_DEVELOPMENT', _('Web Development')
        MOBILE_DEVELOPMENT = 'MOBILE_DEVELOPMENT', _('Mobile Development')
        GAME_DEVELOPMENT = 'GAME_DEVELOPMENT', _('Game Development')
        DEVOPS = 'DEVOPS', _('DevOps')
        DATABASES = 'DATABASES', _('Databases')
        PROGRAMMING_LANGUAGES = 'PROGRAMMING_LANGUAGES', _('Programming Languages')
        OTHER = 'OTHER', _('Other')

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = HTMLField()
    tag = models.CharField(max_length=200, choices=Tags.choices, default=Tags.OTHER)
    banner_image = models.ImageField(upload_to='blogs/banner_images/', blank=True)
    time_to_read = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class Course(models.Model):
    class Types(models.TextChoices):
        PREMIUM = 'PREMIUM', _('Premium')
        GOLD = 'GOLD', _('Gold')
        WORKSHOPS = 'WORKSHOPS', _('Workshops')
        
    title = models.CharField(max_length=200)
    price = models.FloatField()
    description = HTMLField()
    start_date = models.DateField()
    end_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    time_to_complete = models.CharField(max_length=100)
    icon = models.ImageField(upload_to='courses/icons/', blank=True)
    banner_image = models.ImageField(upload_to='courses/banner_images/', blank=True)
    type = models.CharField(max_length=200, choices=Types.choices, default=Types.WORKSHOPS)
    date_created = models.DateTimeField(auto_now_add=True)
    more_info  = models.URLField(blank=True)

    def __str__(self):
        return self.title


class CourseKeyPoint(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    key_point = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.key_point

class ContactUs(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=200)
    message = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

apps/accounts/views.py
from django.shortcuts import render

apps/blogs/views.py
from django.shortcuts import render
from apps.blogs.models import BlogPost, Course, CourseKeyPoint, ContactUs
from apps.accounts.models import Team
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator

class IndexView(ListView):
    model = Team
    template_name = 'index.html'
    context_object_name = 'teams'


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'blogs/blogpost_list.html'
    context_object_name = 'blogposts'
    ordering = ['-date_created']
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        tag = self.request.GET.get('tag')
        if tag:
            queryset = queryset.filter(tag=tag)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        paginator = Paginator(self.object_list, self.paginate_by)
        page_number = self.request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        
        # Calculate the range of page numbers to display
        num_pages = paginator.num_pages
        current_page = page_obj.number
        start_page = max(1, current_page - 2)
        end_page = min(start_page + 2, num_pages)
        
        # Create a list of page numbers
        page_range = range(start_page, end_page + 1)
        
        context['page_obj'] = page_obj
        context['page_range'] = page_range
        
        return context


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blogs/blogpost_detail.html'
    context_object_name = 'blogpost'

    
class CourseListView(ListView):
    model = Course
    template_name = 'courses/course_list.html'
    context_object_name = 'courses'
    ordering = ['-date_created']
    
class CourseDetailView(DetailView):
    model = BlogPost
    template_name = 'blogs/blogpost_detail.html'
    context_object_name = 'blogpost'

class WorkshopListView(ListView):
    model = Course
    template_name = 'workshops/workshop_list.html'
    context_object_name = 'workshops'
    ordering = ['-date_created']

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(type='WORKSHOPS')
        return queryset
    
class WorkshopDetailView(DetailView):
    model = Course
    template_name = 'workshops/workshop_detail.html'
    context_object_name = 'workshops'
    ordering = ['-date_created']

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(type='WORKSHOPS')
        return queryset
    
def contact_us(request):
    context = {'message': ''}
    if request.method == 'POST':
        ContactUs.objects.create(name=request.POST['name'],
                                 email=request.POST['email'],
                                 phone=request.POST['phone'],
                                 message=request.POST['message'])
        context['message'] = 'Thank you for contacting us. We will get back to you soon.'
        return render(request, 'contact_us.html', context=context)
    return render(request, 'contact_us.html', context=context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="NeedDataCommunity">
    <meta name="keywords" content="NeedDataCommunity">
    <meta name="author" content="NeedDataCommunity">
    <link rel="icon" href="{% static 'assets/ndc.jpg' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'assets/ndc.jpg' %}" type="image/x-icon" />
    <title>NeedDataCommunity</title>

    <!--Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700;900&amp;display=swap" rel="stylesheet">

    <!-- bootstrap css -->
    <link id="rtl-link" rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/bootstrap.css' %}">

    <!-- remixicon css -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/remixicon.css' %}">

    <!-- iconsax css -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/iconsax.css' %}" />

    <!-- animation css -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/aos.css' %}">

    <!-- swiper slider css -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendors/swiper-bundle.min.css' %}" />

    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">



</head>

<body>

    {% block content %}
    {% endblock content %}
    
    <!-- Bootstrap js-->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>

    <!-- slider js-->
    <script src="{% static 'assets/js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/custom-slider.js' %}"></script>

    <!-- custom cursor -->
    <script src="{% static 'assets/js/custom-cursor.js' %}"></script>

    <!-- aos animation -->
    <script src="{% static 'assets/js/aos.js' %}"></script>
    <script src="{% static 'assets/js/custom-aos.js' %}"></script>

    <!-- iconsax js -->
    <script src="{% static 'assets/js/iconsax.js' %}"></script>

    <!-- laptop animation js -->
    <script src="{% static 'assets/js/home-animation.js' %}"></script>

    <!-- header sticky js -->
    <script src="{% static 'assets/js/header_sticky.js' %}"></script>

    <!-- pricing js -->
    <script src="{% static 'assets/js/pricing-table.js' %}"></script>

    <!-- Theme js-->
    <script src="{% static 'assets/js/script.js' %}"></script>

</body>


</html>

templates/blogs/blogpost_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'components/header.html' %}

<!-- breadcrumb section start -->
<section class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="breadcrumb-content">
                    <div>
                        <h2><img src="{% static 'assets/images/breadcrumb-title.png' %}" class="img-fluid"
                                alt="title-effect">Latest
                            Project
                        </h2>
                        <p><i class="ri-subtract-line"></i>Discover the most recent blogs about artificial
                            intelligence here.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 d-lg-inline-block d-none">
                <div class="breadcrumb-img">
                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/contact-vector.svg" class="img-fluid"
                        alt="service">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- breadcrumb section end -->


<!-- blog section start -->
<section class="ratio2_1">
    <div class="container">
        <div class="row g-5">
            {% for blog in blogposts %}
            <div class="col-12">
                <div class="blog-listing">
                    <div class="blog-img">
                        <img src="{{ blog.banner_image.url }}" class="img-fluid bg-img" alt="blog">
                        <label>{{ blog.get_tag_display }}</label>
                    </div>
                    <div class="blog-content">
                        <a data-cursor="pointer" class="main-title" href="{% url 'blogpost-detail' blog.pk %}">{{ blog.title }}</a>
                        <p>{{ blog.content|truncatewords:15|safe }}</p>
                        <ul>
                            <li><img src="https://themes.pixelstrap.net/mega_bot/assets/svg/feature/code.svg" class="img-fluid avtar" alt="author">{{ blog.author }}</li>
                            <li><i class="iconsax" data-icon="calendar-add"></i> {{ blog.date_created|date:"d F Y" }}</li>
                            <li><i class="iconsax" data-icon="clock"></i> {{ blog.time_to_read }} min</li>
                        </ul>
                        <a data-cursor="pointer" class="btn-arrow" href="{% url 'blogpost-detail' blog.pk %}">
                            <div class="icon-arrow"><i class="iconsax" data-icon="arrow-up"></i></div>Read more
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if is_paginated %}
        <nav aria-label="Page navigation" class="theme-pagination">
            <ul class="pagination">
                
                <li class="page-item">
                    <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" aria-label="Previous">
                        <span aria-hidden="true">
                            <i class="iconsax" data-icon="chevron-left"></i>
                        </span>
                    </a>
                </li>
                
                {% for page_number in page_range %}
                {% if page_number == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% endif %}
                {% endfor %}
                
                <li class="page-item">
                    <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" aria-label="Next">
                        <span aria-hidden="true"> <i class="iconsax" data-icon="chevron-right"></i></span>
                    </a>
                </li>
                
            </ul>
        </nav>
        {% endif %}
    </div>
</section>
<!-- blog section end -->

{% include 'components/contact-us.html' %}
{% include 'components/footer.html' %}

{% endblock content %}

templates/components/contact-us.html
<!-- contact us start -->
<section class="info-section section-b-space">
    <div class="container">
        <div class="info-box" data-aos="fade-in" data-aos-duration="1000" data-aos-delay="100">
            <div class="hand-effect d-md-block d-none">
                <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/hand.svg" class="img-fluid left-hand"
                    alt="hand">
                <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/hand.svg" class="img-fluid right-hand"
                    alt="hand">
            </div>
            <h2>Ready to <span>move <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/title-effect.svg"
                        class="img-fluid" alt="title-effect"></span>
                ahead?</h2>
            <p>Welcome to the NeedDataCommunity, where we curate a thriving environment for learning across every domain within the vast realm of data science. Join our dynamic community where we offer complimentary workshops in diverse fields, ensuring your knowledge grows exponentially. Explore our premium, in-depth courses that provide an edge in the ever-evolving world of technology.</p>
            <ul>
                <li><img src="https://themes.pixelstrap.net/mega_bot/assets/svg/tick.svg" class="img-fluid"
                        alt="tick">Free projects and workshops</li>
                <li><img src="https://themes.pixelstrap.net/mega_bot/assets/svg/tick.svg" class="img-fluid"
                        alt="tick">Get details on any topic</li>
                <li><img src="https://themes.pixelstrap.net/mega_bot/assets/svg/tick.svg" class="img-fluid"
                        alt="tick">Quick advisor to help you</li>
                <li><img src="https://themes.pixelstrap.net/mega_bot/assets/svg/tick.svg" class="img-fluid"
                        alt="tick">15+ category to explore</li>
            </ul>
            <a data-cursor="pointer" class="btn-arrow" href="{% url 'contact-us' %}">
                <div class="icon-arrow"><i class="iconsax" data-icon="arrow-up"></i></div>Contact us now
            </a>
        </div>
    </div>
</section>
<!-- contact us end -->

templates/components/footer.html
{% load static %}
<!-- footer section start-->
<footer>
    <div class="container">
        <div class="footer-row">
            <div class="footer-main">
                <a href="/" class="footer-logo"><img src="{% static 'assets/need-data-logo.png' %}"
                        class="img-fluid" alt=""></a>
                <h3>Follow us on Linkedin</h3>
                <!-- <form>
                    <div class="input-group">
                        <input type="email" class="form-control" id="exampleFormControlInput1"
                            placeholder="Enter your mail">
                        <a href="#" data-cursor="pointer" class="btn-basic">Subscribe</a>
                    </div>
                </form> -->
                <ul class="social-links">
                    <!-- <li><a data-cursor="pointer" href="https://www.facebook.com/"><img
                                src="https://themes.pixelstrap.net/mega_bot/assets/svg/social/fb.svg" class="img-fluid"
                                alt="facebook"></a></li> -->
                    <li><a data-cursor="pointer" href="https://www.linkedin.com/company/needdata/"><img
                                src="https://themes.pixelstrap.net/mega_bot/assets/svg/social/linkedin.svg"
                                class="img-fluid" alt="linkedin"></a></li>
                    <!-- <li><a data-cursor="pointer" href="https://www.instagram.com/"><img
                                src="https://themes.pixelstrap.net/mega_bot/assets/svg/social/insta.svg"
                                class="img-fluid" alt="insta"></a></li>
                    <li><a data-cursor="pointer" href="https://twitter.com/login"><img
                                src="https://themes.pixelstrap.net/mega_bot/assets/svg/social/twitter.svg"
                                class="img-fluid" alt="twitter"></a></li> -->
                </ul>
            </div>
            <div class="link-section">
                <div class="footer-title">
                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/star.svg" class="img-fluid" alt="star">
                    Quick Link
                </div>
                <div class="footer-content">
                    <ul>
                        <li><a data-cursor="pointer" href="/">Home</a></li>
                        <li><a data-cursor="pointer" href="{% url 'blogpost-list' %}">Projects</a></li>
                        <li><a data-cursor="pointer" href="{% url 'course-list' %}">Courses</a></li>
                        <li><a data-cursor="pointer" href="{% url 'workshop-list' %}">Workshops</a></li>
                        <li><a data-cursor="pointer" href="{% url 'contact-us' %}">Contact us</a></li>
                    </ul>
                </div>
            </div>
            <div class="link-section">
                <!-- <div class="footer-title">
                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/star.svg" class="img-fluid" alt="star">
                    Our service
                </div>
                <div class="footer-content">
                    <ul>
                        <li><a data-cursor="pointer" href="chat.html">Generate</a></li>
                        <li><a data-cursor="pointer" href="chat.html">Find Image</a></li>
                        <li><a data-cursor="pointer" href="chat.html">Email writer</a></li>
                        <li><a data-cursor="pointer" href="chat.html">Social media</a></li>
                    </ul>
                </div> -->
            </div> 
            <div class="link-section">
                <!-- <div class="footer-title">
                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/star.svg" class="img-fluid" alt="star">
                    Our company
                </div>
                <div class="footer-content">
                    <ul>
                        <li><a data-cursor="pointer" href="login.html">Login</a></li>
                        <li><a data-cursor="pointer" href="blog-listing.html">Blog listing</a></li>
                        <li><a data-cursor="pointer" href="blog-grid.html">Blog Grid</a></li>
                        <li><a data-cursor="pointer" href="blog-details.html">Blog Details</a></li>
                    </ul>
                </div> -->
            </div>
        </div>
        <div class="footer-copyright">
            <h4>@2023 All the Copyright Reserved.</h4>
            <!-- <ul class="footer-links">
                <li><a href="terms.html">Privacy Policy </a></li>
                <li><a href="terms.html">Terms & Condition </a></li>
            </ul> -->
        </div>
    </div>
</footer>
<!-- footer section end-->

templates/courses/course_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'components/header.html' %}

<!-- breadcrumb section start -->
<section class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="breadcrumb-content">
                    <div>
                        <h2><img src="{% static 'assets/images/breadcrumb-title.png' %}" class="img-fluid"
                                alt="title-effect">Course Pricing
                        </h2>
                        <p><i class="ri-subtract-line"></i>Select any course from below which is right for you.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 d-lg-inline-block d-none">
                <div class="breadcrumb-img">
                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/pricing-vector.svg" class="img-fluid" alt="service">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- breadcrumb section end -->


<!-- pricing section start -->
<section class="pricing-section pb-md-5 pb-0">
    <div class="container">
        <div class="title-basic fs-sm">
            <h2 class="text-white">Unleash limitless potential & versatile features for every need </h2>
        </div>
        <div class="row pricing-row g-xl-5 g-4 justify-content-center">
            {% for course in courses %}
            {% if course.type == "GOLD" %}
            <div class="col-lg-4 col-md-6">
                <div class="pricing-box">
                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/hanging.svg" class="img-fluid handing-cls" alt="effect">
                    <div class="pricing-top">
                        <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/pricing/pricing-top.svg" class="img-fluid pricing-bg" alt="">
                        <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/pricing/weekly.svg" class="img-fluid" alt="">
                        <h3>&#8377; {{ course.price }}</h3>
                    </div>
                    <div class="pricing-mid">
                        <div class="clip-path-content">
                            <div>
                                <h2>{{ course.title }}</h2>
                                <h4></h4>
                            </div>
                        </div>
                    </div>
                    <div class="pricing-content">
                        <div class="clip-path-content">
                            <ul>
                                {% for feature in course.coursekeypoint_set.all %}
                                <li>
                                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/arrow.svg" class="img-fluid" alt="arrow">
                                    <h4>{{ feature.key_point }}</h4>
                                </li>
                                {% endfor %}
                            </ul>
                            <a class="pricing-link" href="{{ course.more_info }}" data-cursor="pointer">More Info</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if course.type == "PREMIUM" %}
            <div class="col-lg-4 col-md-6">
                <div class="pricing-box">
                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/hanging-green.svg" class="img-fluid handing-cls" alt="effect">
                    <div class="pricing-top">
                        <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/pricing/pricing-center.svg" class="img-fluid pricing-bg" alt="">
                        <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/pricing/monthly.svg" class="img-fluid" alt="">
                        <h3>&#8377; {{ course.price }}</h3>
                    </div>
                    <div class="pricing-mid">
                        <div class="clip-path-content">
                            <div>
                                <h2>{{ course.title }}</h2>
                                <h4></h4>
                            </div>
                        </div>
                    </div>
                    <div class="pricing-content">
                        <div class="clip-path-content">
                            <ul>
                                {% for feature in course.coursekeypoint_set.all %}
                                <li>
                                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/arrow.svg" class="img-fluid" alt="arrow">
                                    <h4>{{ feature.key_point }}</h4>
                                </li>
                                {% endfor %}
                            </ul>
                            <a class="pricing-link" href="{{ course.more_info }}" data-cursor="pointer">More Info</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            <!--
            <div class="col-lg-4 col-md-6">
                <div class="pricing-box">
                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/hanging.svg" class="img-fluid handing-cls" alt="effect">
                    <div class="pricing-top">
                        <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/pricing/pricing-top.svg" class="img-fluid pricing-bg" alt="">
                        <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/pricing/yearly.svg" class="img-fluid" alt="">
                        <h3>Lifetime Plan</h3>
                    </div>
                    <div class="pricing-mid">
                        <div class="clip-path-content">
                            <div>
                                <h2>$3.99</h2>
                                <h4>/ only</h4>
                            </div>
                        </div>
                    </div>
                    <div class="pricing-content">
                        <div class="clip-path-content">
                            <ul>
                                <li>
                                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/arrow.svg" class="img-fluid" alt="arrow">
                                    <h4>Intelligent AI chatbot</h4>
                                </li>
                                <li>
                                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/arrow.svg" class="img-fluid" alt="arrow">
                                    <h4>Unlimited answer of question</h4>
                                </li>
                                <li>
                                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/arrow.svg" class="img-fluid" alt="arrow">
                                    <h4>Avoid buying coin forever</h4>
                                </li>
                                <li>
                                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/arrow.svg" class="img-fluid" alt="arrow">
                                    <h4>No ad in background</h4>
                                </li>
                                <li>
                                    <img src="https://themes.pixelstrap.net/mega_bot/assets/svg/arrow.svg" class="img-fluid" alt="arrow">
                                    <h4>Early access to new features</h4>
                                </li>
                            </ul>
                            <a class="pricing-link" href="#" data-cursor="pointer">Choose plan</a>
                        </div>
                    </div>
                </div>
            </div> -->
            {% endfor %}
        </div>
    </div>
</section>
<!-- pricing section end -->

{% include 'components/contact-us.html' %}
{% include 'components/footer.html' %}

{% endblock content %}